# ZyzDisplay overlay values for /etc/bluetooth/main.conf
Name = ZyzDisplay
Class = 0x240414
DiscoverableTimeout = 0
AlwaysPairable = true
JustWorksRepairing = always
FastConnectable = true
AutoEnable=true
